//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wep_Api_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sepet
    {
        public int SepetID { get; set; }
        public string KullaniciID { get; set; }
        public int UrunID { get; set; }
        public int Adet { get; set; }
        public int ToplamTutar { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
